# Generated by Django 2.1 on 2018-08-24 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_path', models.FilePathField(path='/backend/static/images/movie-posters')),
                ('summary', models.TextField(max_length=1000)),
                ('release_year', models.CharField(max_length=4)),
                ('length', models.CharField(max_length=8)),
                ('genres', models.CharField(max_length=80)),
                ('imdb_url', models.URLField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account'},
        ),
        migrations.AddField(
            model_name='movie',
            name='checklist_movies',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
