# Generated by Django 2.1 on 2018-09-13 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'unique': 'Username is already taken.'}, help_text='Required. 30 characters or fewer. Letters, digits, periods, and underscores only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.]+$', 'Username may only contain letters, numbers, periods, and underscores.', 'invalid')]),
        ),
    ]
