# Generated by Django 2.1 on 2018-08-24 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180824_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='checklist_movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='movies',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
