# Generated by Django 2.1 on 2018-08-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180824_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
