# Generated by Django 2.1 on 2018-08-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_path',
            field=models.FilePathField(path='/backend/backend/static/images/movie-posters'),
        ),
    ]
