# Generated by Django 2.1 on 2018-08-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180824_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_path',
            field=models.FilePathField(path='/Users/bk/Desktop/1001MoviesChecklist/backend/backend/static/images/movie-posters'),
        ),
    ]
