# Generated by Django 2.1 on 2018-08-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180824_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movies',
            new_name='user',
        ),
    ]
