const ACTION_TYPES = {
  TOGGLE_SIGNUP: 'TOGGLE_SIGNUP',
  CLOSE_SIGNUP: 'CLOSE_SIGNUP',
  TOGGLE_LOGIN: 'TOGGLE_LOGIN',
  CLOSE_LOGIN: 'CLOSE_LOGIN',
  TOGGLE_PASSWORD_RESET_REQUEST: 'TOGGLE_PASSWORD_RESET_REQUEST',
  CLOSE_PASSWORD_RESET_REQUEST: 'CLOSE_PASSWORD_RESET_REQUEST',
  SIGNUP: 'SIGNUP',
  LOGIN: 'LOGIN',
  GET_USER_INFO: 'GET_USER_INFO',
  LOGOUT: 'LOGOUT',
  SEND_EMAIL_VERIFY_LINK: 'SEND_EMAIL_VERIFY_LINK',
  CONFIRM_EMAIL_VERIFY: 'CONFIRM_EMAIL_VERIFY',
  SEND_PASSWORD_RESET_LINK: 'SEND_PASSWORD_RESET_LINK',
  CONFIRM_PASSWORD_RESET: 'CONFIRM_PASSWORD_RESET',
  CONFIRM_CREDENTIALS_DELETE_ACCOUNT: 'CONFIRM_CREDENTIALS_DELETE_ACCOUNT',
  CONFIRM_CREDENTIALS_CHANGE_PASSWORD: 'CONFIRM_CREDENTIALS_CHANGE_PASSWORD',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT'
};

export default ACTION_TYPES;