const ACTION_TYPES = {
  TOGGLE_SIGNUP: 'TOGGLE_SIGNUP',
  TOGGLE_LOGIN: 'TOGGLE_LOGIN',
  CLOSE_LOGIN: 'CLOSE_LOGIN',
  CLOSE_SIGNUP: 'CLOSE_SIGNUP',
  SIGNUP: 'SIGNUP',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
};

export default ACTION_TYPES;