const ACTION_TYPES = {
  TOGGLE_SIGNUP: 'TOGGLE_SIGNUP',
  TOGGLE_LOGIN: 'TOGGLE_LOGIN',
  TOGGLE_RESET: 'TOGGLE_RESET',
  CLOSE_LOGIN: 'CLOSE_LOGIN',
  CLOSE_SIGNUP: 'CLOSE_SIGNUP',
  CLOSE_RESET: 'CLOSE_RESET',
  SIGNUP: 'SIGNUP',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CONFIRM_VERIFY_EMAIL: 'CONFIRM_VERIFY_EMAIL',
  SEND_RESET_PASSWORD_LINK: 'SEND_RESET_PASSWORD_LINK',
  CONFIRM_RESET_PASSWORD: 'CONFIRM_RESET_PASSWORD',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  GET_USER_INFO: 'GET_USER_INFO'
};

export default ACTION_TYPES;